theme: jekyll-theme-minimal
url: https://dl.acm.org/doi/10.1145/3392854
description: "Data to accompany the CSCW paper <a href="https://dl.acm.org/doi/10.1145/3392854>  Measuring Misinformation in Video Search Platforms: An Audit Study on YouTube." </a>
