theme: jekyll-theme-minimal
#redirect: https://dl.acm.org/doi/10.1145/3392854
#show_downloads: true
#description: "Data to accompany the CSCW paper  Measuring Misinformation in Video Search Platforms: An Audit Study on YouTube." #https://dl.acm.org/doi/10.1145/3392854
description: "[My name here](https://dl.acm.org/doi/10.1145/3392854)  \n[I'm on Twitter](https://dl.acm.org/doi/10.1145/3392854)"
- label: "LinkedIn"
  icon: "fab fa-fw fa-linkedin"
  url: "https://www.linkedin.com/in/leonardojhernandez"
