theme: jekyll-theme-minimal
#redirect: https://dl.acm.org/doi/10.1145/3392854
#show_downloads: true
#description: "Data to accompany the CSCW paper Measuring Misinformation in Video Search Platforms: An Audit Study on YouTube." \
#"link: https://dl.acm.org/doi/10.1145/3392854"
description: |
    Data to accompany the CSCW 2020 paper Measuring Misinformation in Video Search Platforms: An Audit Study on YouTube.
    url: https://dl.acm.org/doi/10.1145/3392854
    
